FROM ubuntu
#FROM ubuntu/after_install3
#RUN apt-get update
#RUN apt-get install -y git neovim wget zsh
#RUN apt-get install -y git curl neovim zsh locales thefuck htop tmux packagekit-command-not-found command-not-found python-pip libsecret-1-0 libsecret-1-dev

#ADD . /root/
#RUN ["/root/develop-environment-setup.sh"]

#FROM ubuntu/after_install2
ADD .. /
